### ISSUE TITLE
Index exceeds array bounds.

### ISSUE THREAD

**Issue by dimitargslavchev** [YingzhouLi/meshpart#1] opened 2020-04-09 16:28 UTC
I get the following error when I run nested dissection with

nd = geond(AAA, transpose(inter_p));

I can see that
quality = sepquality(v,A,xyz);

is passed an 9x9 matrix A, but xyz are for 10 elements.

I am adding the matrix and the points bellow.

[matrix_for_meshpart.zip](https://github.com/YingzhouLi/meshpart/files/4457433/matrix_for_meshpart.zip)

```
Error Bellow:
Index exceeds array bounds.

Error in sepquality (line 16)
cutsize = nnz(A(a,b)|A(b,a)');

Error in sepcircle (line 40)
        quality = sepquality(v,A,xyz);

Error in geopart (line 70)
    [greatcircle,gcquality] = sepcircle(A,xyzmap,ninner);

Error in ndperm (line 55)
        part = feval(method, Asub, vararginsub{:});

Error in ndperm (line 67)
        q1 = ndperm(method,minsep,Asubp1,vararginsubp1{:});

Error in ndperm (line 76)
        q2 = ndperm(method,minsep,Asubp2,vararginsubp2{:});

Error in ndperm (line 76)
        q2 = ndperm(method,minsep,Asubp2,vararginsubp2{:});

Error in ndperm (line 67)
        q1 = ndperm(method,minsep,Asubp1,vararginsubp1{:});

Error in ndperm (line 76)
        q2 = ndperm(method,minsep,Asubp2,vararginsubp2{:});

Error in ndperm (line 76)
        q2 = ndperm(method,minsep,Asubp2,vararginsubp2{:});

Error in ndperm (line 67)
        q1 = ndperm(method,minsep,Asubp1,vararginsubp1{:});

Error in ndperm (line 67)
        q1 = ndperm(method,minsep,Asubp1,vararginsubp1{:});

Error in ndperm (line 67)
        q1 = ndperm(method,minsep,Asubp1,vararginsubp1{:});


Error in geond (line 30)
p = ndperm('geopart',minsep,A,Axy,ntries);

Error in calculate_nd (line 41)
nd = geond(AAA, transpose(inter_p));
```

**Comment by YingzhouLi** [comment] 2020-04-09 19:29
@Tarkalak This is indeed caused by a bug in the code. It has been fixed in the new pull request.

**Closed as completed** 2020-04-09 19:30 UTC
Labels: bug

**Comment by dimitargslavchev** [comment] 2020-04-10 13:28
Thank you.
